/*
 * File: MyViewport.ui.js
 * Date: Mon Jun 21 2010 18:15:20 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.1.0c.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyViewportUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'CMDB',
                layout: 'auto',
                region: 'center',
                items: [
                    {
                        xtype: 'panel',
                        id: 'main_panel'
                    },
                    {
                        xtype: 'tabpanel',
                        activeTab: 0,
                        id: 'tab_panel',
                        items: [
                            {
                                xtype: 'panel',
                                title: 'Details',
                                items: [
                                    {
                                        xtype: 'form',
                                        labelWidth: 100,
                                        labelAlign: 'left',
                                        layout: 'form',
                                        padding: '10px',
                                        autoScroll: true,
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                title: 'General',
                                                layout: 'form',
                                                collapsible: true,
                                                animCollapse: true,
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Name',
                                                        anchor: '100%',
                                                        name: 'name'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Serial Number',
                                                        anchor: '100%',
                                                        name: 'serial_number'
                                                    },
                                                    {
                                                        xtype: 'combo',
                                                        fieldLabel: 'Company',
                                                        anchor: '100%',
                                                        name: 'company'
                                                    },
                                                    {
                                                        xtype: 'combo',
                                                        fieldLabel: 'Location',
                                                        anchor: '100%',
                                                        name: 'location'
                                                    },
                                                    {
                                                        xtype: 'combo',
                                                        fieldLabel: 'Model',
                                                        anchor: '100%',
                                                        name: 'model'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Machine Type',
                                                        anchor: '100%',
                                                        name: 'machine_type'
                                                    },
                                                    {
                                                        xtype: 'checkbox',
                                                        fieldLabel: 'Compliance In Scope',
                                                        boxLabel: '',
                                                        anchor: '100%',
                                                        name: 'in_scope'
                                                    },
                                                    {
                                                        xtype: 'textarea',
                                                        fieldLabel: 'IP Addresses',
                                                        anchor: '100%',
                                                        name: 'ip_addresses'
                                                    },
                                                    {
                                                        xtype: 'textarea',
                                                        fieldLabel: 'Documentation URLs',
                                                        anchor: '100%',
                                                        name: 'url'
                                                    },
                                                    {
                                                        xtype: 'textarea',
                                                        fieldLabel: 'Description',
                                                        anchor: '100%',
                                                        name: 'description'
                                                    },
                                                    {
                                                        xtype: 'textarea',
                                                        fieldLabel: 'Alert Groups',
                                                        anchor: '100%',
                                                        name: 'alert_group'
                                                    },
                                                    {
                                                        xtype: 'textarea',
                                                        fieldLabel: 'Notify Groups',
                                                        anchor: '100%',
                                                        name: 'notify_group'
                                                    },
                                                    {
                                                        xtype: 'textarea',
                                                        fieldLabel: 'Escalation Groups',
                                                        anchor: '100%',
                                                        name: 'escalation_group'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                title: 'Asset Management',
                                                layout: 'form',
                                                collapsible: true,
                                                animCollapse: true,
                                                items: [
                                                    {
                                                        xtype: 'datefield',
                                                        fieldLabel: 'Warranty Expire',
                                                        anchor: '100%',
                                                        name: 'warranty_expire'
                                                    },
                                                    {
                                                        xtype: 'datefield',
                                                        fieldLabel: 'Purchase Date',
                                                        anchor: '100%',
                                                        name: 'purchase_date'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Department',
                                                        anchor: '100%',
                                                        name: 'department'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Asset Tag',
                                                        anchor: '100%',
                                                        name: 'asset_tag'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'SOC/PO Number',
                                                        anchor: '100%',
                                                        name: 'soc_number'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                title: 'Server Information',
                                                layout: 'form',
                                                animCollapse: true,
                                                collapsible: true,
                                                items: [
                                                    {
                                                        xtype: 'combo',
                                                        fieldLabel: 'Deployment Status',
                                                        anchor: '100%',
                                                        name: 'deployment_status'
                                                    },
                                                    {
                                                        xtype: 'combo',
                                                        fieldLabel: 'Operating System',
                                                        anchor: '100%',
                                                        name: 'operating_system'
                                                    },
                                                    {
                                                        xtype: 'combo',
                                                        fieldLabel: 'Authentication Source',
                                                        anchor: '100%',
                                                        name: 'authentication_source'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                title: 'Advanced',
                                                layout: 'form',
                                                collapsible: true,
                                                animCollapse: true,
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Extension Attribute 1',
                                                        anchor: '100%',
                                                        name: 'extension_attribute_1'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Extension Attribute 2',
                                                        anchor: '100%',
                                                        name: 'extension_attribute_2'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Extension Attribute 3',
                                                        anchor: '100%',
                                                        name: 'extension_attribute_3'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Extension Attribute 4',
                                                        anchor: '100%',
                                                        name: 'extension_attribute_4'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Extension Attribute 5',
                                                        anchor: '100%',
                                                        name: 'extension_attribute_5'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Extension Attribute 6',
                                                        anchor: '100%',
                                                        name: 'extension_attribute_6'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Extension Attribute 7',
                                                        anchor: '100%',
                                                        name: 'extension_attribute_7'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Extension Attribute 8',
                                                        anchor: '100%',
                                                        name: 'extension_attribute_8'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Extension Attribute 9',
                                                        anchor: '100%',
                                                        name: 'extension_attribute_9'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Extension Attribute 10',
                                                        anchor: '100%',
                                                        name: 'extension_attribute_10'
                                                    },
                                                    {
                                                        xtype: 'checkbox',
                                                        fieldLabel: 'Extension Attribute 11',
                                                        boxLabel: '',
                                                        anchor: '100%',
                                                        name: 'extenstion_attribute_11'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                title: 'History',
                                items: [
                                    {
                                        xtype: 'panel',
                                        title: '',
                                        layout: 'border',
                                        height: 400,
                                        id: 'history_panel',
                                        items: [
                                            {
                                                xtype: 'grid',
                                                title: '',
                                                store: 'DeploymentStatusStore',
                                                region: 'west',
                                                width: 514,
                                                columns: [
                                                    {
                                                        xtype: 'gridcolumn',
                                                        header: 'Date',
                                                        sortable: true,
                                                        resizable: true,
                                                        width: 100,
                                                        dataIndex: 'string'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        header: 'User',
                                                        sortable: true,
                                                        resizable: true,
                                                        width: 100,
                                                        dataIndex: 'string'
                                                    },
                                                    {
                                                        xtype: 'gridcolumn',
                                                        header: 'Update',
                                                        sortable: true,
                                                        resizable: true,
                                                        width: 100,
                                                        dataIndex: 'string'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                autoEl: 'div',
                                                region: 'center',
                                                id: 'history_detail'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                title: 'Change'
                            },
                            {
                                xtype: 'panel',
                                title: 'Incidents'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'treepanel',
                title: 'My Tree',
                region: 'west',
                width: 155,
                collapsible: true,
                id: 'tree_panel',
                root: {
                    text: 'Root Node'
                },
                loader: {

                }
            }
        ];
        MyViewportUi.superclass.initComponent.call(this);
    }
});
