/*
 * File: xds_index.js
 * Date: Mon Jun 21 2010 18:15:20 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.1.0c.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    var myViewport = new MyViewport({
        renderTo: Ext.getBody()
    });
    myViewport.show();
});
